# Generated by Django 5.2.4 on 2025-09-02 14:03

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('start_datetime', models.DateTimeField(db_index=True, unique=True)),
                ('cancel_code', models.CharField(db_index=True, default=core.models.generate_cancel_code, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
