# Generated by Django 5.2.4 on 2025-09-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='category',
            field=models.CharField(choices=[('cbt', 'Cognitive Behavioral Therapy'), ('couples', 'Couples Counseling'), ('mindfulness', 'Mindfulness Therapy')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
