# Generated by Django 5.2.4 on 2025-09-04 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='category',
        ),
    ]
