# Generated by Django 5.2.4 on 2025-09-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_appointment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session_format',
            field=models.CharField(choices=[('face_to_face', 'Face to Face Session'), ('online', 'Online Session')], default='face_to_face', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='therapy_type',
            field=models.CharField(choices=[('cbt', 'Cognitive Behavioral Therapy'), ('couples', 'Couples Counseling'), ('mindfulness', 'Mindfulness Therapy')], default='cbt', max_length=20),
        ),
    ]
